# Change 'comments' to true for Disqus comments
# disqus:
#   comments: false
#   disqus_shortname: 'millennial-3'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: 'G-G1JD2R3080'

menu:
- {name: 'arXiv', url: 'arxiv'}
- {name: 'Essay', url: 'essay'}
- {name: 'Photography', url: 'photography'}
- {name: 'About', url: 'about'}
- {name: 'Contact', url: 'contact'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'twitter', link:    'https://twitter.com/Reself_C'}
# - {icon: 'facebook', link:   'https://www.facebook.com/paululele'}
# - {icon: 'instagram', link:  'https://instagram.com/paululele'}
- {icon: 'envelope', link:   'reselfchai@gmail.com'}
- {icon: 'github', link: 'https://github.com/Reself-C'}
- {icon: 'linkedin', link: 'https://www.linkedin.com/in/wenhao-chai-658274238/'}
# - {icon: 'rss-square', link: 'feed.xml'}
# - {icon: 'rss-square', link: 'rss-feed.xml'}

# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'

sharing_button_prompt: 'Feel free to share!'

related_posts: 'You may also enjoy...'

post_date_prefix: 'Written on'
